spring:
  security:
    user:
      name: admin
      password: my-secret-password
      roles: ADMIN
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  sleuth:
    sampler:
      probability: 1.0
server:
  servlet:
    context-path: /api
  max-http-request-header-size: 16KB
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: 'info, health, beans'
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

application:
  config:
    posts:
      baseUrl: https://jsonplaceholder.typicode.com
      auditionPosts: /posts
      auditionComments: /comments
    interceptor:
      logRequest: true
      logResponse: true